/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressForm: typeof import('./src/components/auth/AddressForm.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    ApplicationDeadlinesInfo: typeof import('./src/components/application/ApplicationDeadlinesInfo.vue')['default']
    ApplicationHeader: typeof import('./src/components/application/ApplicationHeader.vue')['default']
    ApplicationStepHeader: typeof import('./src/components/application/ApplicationStepHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AuthHeader: typeof import('./src/components/auth/AuthHeader.vue')['default']
    AuthHero: typeof import('./src/components/auth/AuthHero.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseFooter: typeof import('./src/components/layout/BaseFooter.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ContactInformationForm: typeof import('./src/components/auth/ContactInformationForm.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    ForgotPasswordForm: typeof import('./src/components/auth/ForgotPasswordForm.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSelector: typeof import('./src/components/features/LanguageSelector.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    MajorPrioritySidebar: typeof import('./src/components/application/MajorPrioritySidebar.vue')['default']
    MajorSelectionTable: typeof import('./src/components/application/MajorSelectionTable.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    OrderList: typeof import('primevue/orderlist')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    PersonalDataForm: typeof import('./src/components/auth/PersonalDataForm.vue')['default']
    PersonalInformationForm: typeof import('./src/components/auth/PersonalInformationForm.vue')['default']
    ResetPasswordForm: typeof import('./src/components/auth/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SidebarFooter: typeof import('./src/components/sidebar/SidebarFooter.vue')['default']
    SidebarLink: typeof import('./src/components/sidebar/SidebarLink.vue')['default']
    SidebarLinks: typeof import('./src/components/sidebar/SidebarLinks.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Step: typeof import('primevue/step')['default']
    StepItem: typeof import('primevue/stepitem')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeSwitcher: typeof import('./src/components/features/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UniversityHeader: typeof import('./src/components/ui/UniversityHeader.vue')['default']
    UniversityIcon: typeof import('./src/components/ui/UniversityIcon.vue')['default']
    UniversityLogo: typeof import('./src/components/ui/UniversityLogo.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
