/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/forgot-password': RouteRecordInfo<
      '/(auth)/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/login': RouteRecordInfo<
      '/(auth)/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/register': RouteRecordInfo<
      '/(auth)/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/reset-password': RouteRecordInfo<
      '/(auth)/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/': RouteRecordInfo<
      '/(main)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/application/education': RouteRecordInfo<
      '/(main)/application/education',
      '/application/education',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/application/study-programs': RouteRecordInfo<
      '/(main)/application/study-programs',
      '/application/study-programs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/major/': RouteRecordInfo<
      '/(main)/major/',
      '/major',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/major/[id]': RouteRecordInfo<
      '/(main)/major/[id]',
      '/major/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(main)/profile': RouteRecordInfo<
      '/(main)/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(auth)/forgot-password.vue': {
      routes:
        | '/(auth)/forgot-password'
      views:
        | never
    }
    'src/pages/(auth)/login.vue': {
      routes:
        | '/(auth)/login'
      views:
        | never
    }
    'src/pages/(auth)/register.vue': {
      routes:
        | '/(auth)/register'
      views:
        | never
    }
    'src/pages/(auth)/reset-password.vue': {
      routes:
        | '/(auth)/reset-password'
      views:
        | never
    }
    'src/pages/(main)/index.vue': {
      routes:
        | '/(main)/'
      views:
        | never
    }
    'src/pages/(main)/application/education.vue': {
      routes:
        | '/(main)/application/education'
      views:
        | never
    }
    'src/pages/(main)/application/study-programs.vue': {
      routes:
        | '/(main)/application/study-programs'
      views:
        | never
    }
    'src/pages/(main)/major/index.vue': {
      routes:
        | '/(main)/major/'
      views:
        | never
    }
    'src/pages/(main)/major/[id].vue': {
      routes:
        | '/(main)/major/[id]'
      views:
        | never
    }
    'src/pages/(main)/profile.vue': {
      routes:
        | '/(main)/profile'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
